# Generated by Django 4.2.6 on 2024-02-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApiApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
