# Generated by Django 4.2.6 on 2024-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginApiApp', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=50, null=True)),
                ('createdat', models.DateTimeField(db_column='CreatedAt')),
                ('updatedat', models.DateTimeField(db_column='UpdatedAt')),
                ('role', models.CharField(blank=True, db_column='Role', max_length=5, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
