# Generated by Django 4.2.6 on 2024-02-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApiApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
